services:
  - type: web
    name: flutter-web
    env: static
    buildCommand: |
      # Install Flutter manually
      git clone https://github.com/flutter/flutter.git
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter build web
    staticPublishPath: build/web
